// Governance Compiler — Entry point
// Import: change App to GovernanceCompiler in this file if main.jsx points to App
import { useState, useCallback } from "react";
const D={
  "co-parenting":["Behavioral Consistency","Communication Pattern","Control Dynamics","Child Impact","Structural Capacity"],
  "team-health":["Role Distribution","Communication Health","Workload Balance","Psychological Safety","Decision Quality"],
  "product-quality":["User Experience","Technical Reliability","Brand Alignment","Accessibility","Performance"],
  "illustration":["Palette Alignment","Geometry Compliance","Atmosphere Match","Composition Fidelity","Texture Coherence","Key Element Presence"],
  "narrative":["Character Consistency","Plot Logic","Thematic Coherence","Emotional Trajectory","World-Rule Compliance"],
  "custom":[]
};
const W={"co-parenting":[.25,.15,.20,.25,.15],"team-health":[.20,.20,.20,.20,.20],"product-quality":[.25,.20,.20,.15,.20],"illustration":[.20,.15,.15,.15,.10,.25],"narrative":[.25,.25,.20,.15,.15],"custom":[]};
const CF={"co-parenting":.99,"team-health":.95,"product-quality":.95,"illustration":.90,"narrative":.90,"custom":.95};
const SIG=[{code:"H*",label:"Fatal disqualifier",lr:.03,color:"#e04040"},{code:"X",label:"Strong negative",lr:.12,color:"#d07070"},{code:"M",label:"Moderate negative",lr:.35,color:"#c8a060"},{code:"W",label:"Weak signal",lr:.65,color:"#a0a090"},{code:"N",label:"Noise",lr:1.0,color:"#808080"},{code:"S",label:"Weak positive",lr:1.6,color:"#90a0c0"},{code:"F",label:"Moderate positive",lr:3.0,color:"#70a070"},{code:"V",label:"Strong positive",lr:6.0,color:"#50a050"},{code:"C",label:"Cost-bearing positive",lr:10.0,color:"#308030"}];
const ST=["Domain Select","Intake","Score","Align","Weigh","Rule","Residual","Output"];
export default function GovernanceCompiler(){
  const[stage,setStage]=useState(0);const[ct,setCt]=useState("");const[cn,setCn]=useState("");const[doms,setDoms]=useState([]);const[wts,setWts]=useState([]);const[conf,setConf]=useState(.95);const[ev,setEv]=useState({});const[sc,setSc]=useState({});const[sg,setSg]=useState({});const[rul,setRul]=useState("");const[fal,setFal]=useState("");const[res,setRes]=useState([]);
  const sel=useCallback(t=>{setCt(t);const d=D[t]||[];setDoms(d);setWts(W[t]||d.map(()=>1/d.length));setConf(CF[t]||.95);const e={},s={},g={};d.forEach(x=>{e[x]="";s[x]=50;g[x]="N"});setEv(e);setSc(s);setSg(g)},[]);
  const llr=doms.reduce((a,d)=>{const s=SIG.find(x=>x.code===sg[d]);return a+(s?Math.log(s.lr):0)},0);
  const comp=doms.reduce((a,d,i)=>a+sc[d]*(wts[i]||0),0);
  const bound=Math.log((1/(1-conf))/(1-conf));const prob=1/(1+Math.exp(-llr));
  const sprt=llr>=bound?"EXIT_POSITIVE":llr<=-bound?"EXIT_NEGATIVE":"CONTINUE";
  const hr=[];doms.forEach(d=>{if(sg[d]==="H*")hr.push("Fatal: "+d)});if(doms.filter(d=>sg[d]==="X").length>=3)hr.push("3+ strong negatives");
  const addR=()=>setRes([...res,{desc:"",cat:"data_gap",str:"",goal:""}]);
  const upR=(i,f,v)=>{const r=[...res];r[i]={...r[i],[f]:v};setRes(r)};
  const ok=rul.length>10&&fal.length>10&&res.every(r=>r.str.length>5);
  const B=({onClick:o,children:c,disabled:x})=><button onClick={o} disabled={x} className="px-6 py-2 bg-amber-400/10 border border-amber-400/30 text-amber-300 text-sm rounded disabled:opacity-30">{c}</button>;
  const P=({children:c,className:x=""})=><div className={"p-4 bg-gray-900 border border-gray-800 rounded "+x}>{c}</div>;
  return(<div className="min-h-screen bg-gray-950 text-gray-200 p-4 md:p-8"><div className="max-w-4xl mx-auto">
    <div className="mb-8"><h1 className="text-2xl font-light tracking-wide text-amber-200">Governance Compiler</h1><p className="text-xs text-gray-500 mt-1 tracking-widest uppercase">Multi-Domain Judicial Architecture v1.0</p></div>
    <div className="flex gap-1 mb-8 overflow-x-auto pb-2">{ST.map((s,i)=><button key={s} onClick={()=>i<=stage&&setStage(i)} className={`px-3 py-1.5 text-xs tracking-wider uppercase whitespace-nowrap border rounded ${i===stage?"border-amber-400 text-amber-300 bg-amber-400/10":i<stage?"border-gray-700 text-gray-400":"border-gray-800 text-gray-700"}`}>{i+1}. {s}</button>)}</div>
    {stage===0&&<div><h2 className="text-lg font-light text-gray-300 mb-4">Select Domain</h2><div className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-6">{Object.keys(D).map(t=><button key={t} onClick={()=>sel(t)} className={`p-4 border rounded text-left ${ct===t?"border-amber-400 bg-amber-400/5":"border-gray-800 hover:border-gray-600"}`}><div className="text-sm font-medium capitalize">{t.replace("-"," ")}</div><div className="text-xs text-gray-500 mt-1">{(D[t]||[]).length||"Custom"} domains</div></button>)}</div><input value={cn} onChange={e=>setCn(e.target.value)} placeholder="Case name..." className="w-full bg-gray-900 border border-gray-800 rounded px-4 py-2 text-sm mb-4"/><B onClick={()=>ct&&cn&&setStage(1)} disabled={!ct||!cn}>Proceed to Intake</B></div>}
    {stage===1&&<div><h2 className="text-lg font-light text-gray-300 mb-4">Stage 1: Intake</h2><p className="text-xs text-gray-500 mb-6">Enter evidence per domain.</p>{doms.map(d=><div key={d} className="mb-4"><label className="text-xs text-gray-400 uppercase tracking-wider">{d}</label><textarea value={ev[d]||""} onChange={e=>setEv({...ev,[d]:e.target.value})} rows={3} placeholder={"Evidence for "+d} className="w-full bg-gray-900 border border-gray-800 rounded px-3 py-2 text-sm mt-1"/></div>)}<P><div className="text-xs text-gray-400 uppercase mb-2">Intake Summary</div><div className="text-xs">Received: {doms.filter(d=>ev[d]?.length>0).length}/{doms.length} | Missing: {doms.filter(d=>!ev[d]?.length).join(", ")||"None"}</div></P><div className="mt-4"><B onClick={()=>setStage(2)}>Proceed to Score</B></div></div>}
    {stage===2&&<div><h2 className="text-lg font-light text-gray-300 mb-4">Stage 2: Score</h2>{doms.map(d=><P key={d} className="mb-5"><div className="text-sm font-medium mb-3">{d}</div><div className="flex flex-wrap gap-2 mb-3">{SIG.map(s=><button key={s.code} onClick={()=>setSg({...sg,[d]:s.code})} className={`px-2 py-1 text-xs border rounded ${sg[d]===s.code?"border-amber-400 bg-amber-400/10":"border-gray-700"}`} style={{color:s.color}}>{s.code}</button>)}</div><div className="flex items-center gap-3"><input type="range" min={0} max={100} value={sc[d]||50} onChange={e=>setSc({...sc,[d]:+e.target.value})} className="flex-1"/><span className="text-sm w-10 text-right">{sc[d]}</span></div></P>)}<P><div className="text-xs text-gray-400 uppercase mb-2">Bayesian</div><div className="text-xs">LLR: <span className={llr>0?"text-green-400":"text-red-400"}>{llr.toFixed(3)}</span> | P(+): {(prob*100).toFixed(1)}% | SPRT: <span className={sprt.includes("POS")?"text-green-400":sprt.includes("NEG")?"text-red-400":"text-amber-400"}>{sprt}</span></div></P><div className="mt-4"><B onClick={()=>setStage(3)}>Proceed to Align</B></div></div>}
    {stage===3&&<div><h2 className="text-lg font-light text-gray-300 mb-4">Stage 3: Align</h2><P className="mb-4"><div className="text-xs text-gray-400 uppercase mb-3">Hard Rules</div>{hr.length===0?<div className="text-green-400 text-sm">No violations</div>:hr.map((r,i)=><div key={i} className="text-red-400 text-sm">{r}</div>)}</P><P className="mb-4">{doms.map(d=>{const s=SIG.find(x=>x.code===sg[d]);const n=s&&s.lr<.5;return<div key={d} className="flex justify-between py-2 border-b border-gray-800 last:border-0"><span className="text-sm">{d}</span><span className={`text-xs px-2 py-0.5 rounded ${n?"bg-red-400/10 text-red-400":"bg-green-400/10 text-green-400"}`}>{n?"MISALIGNED":"ALIGNED"}</span></div>})}</P><B onClick={()=>setStage(4)}>Proceed to Weigh</B></div>}
    {stage===4&&<div><h2 className="text-lg font-light text-gray-300 mb-4">Stage 4: Weigh</h2><P className="mb-4"><table className="w-full text-sm"><thead><tr className="text-gray-500 text-xs"><th className="text-left py-1">Domain</th><th className="text-right">Score</th><th className="text-right">Wt</th><th className="text-right">Wtd</th></tr></thead><tbody>{doms.map((d,i)=><tr key={d} className="border-t border-gray-800"><td className="py-1.5">{d}</td><td className="text-right">{sc[d]}</td><td className="text-right text-gray-500">{(wts[i]*100).toFixed(0)}%</td><td className="text-right text-amber-300">{(sc[d]*wts[i]).toFixed(1)}</td></tr>)}<tr className="border-t-2 border-gray-600 font-medium"><td className="py-2">COMPOSITE</td><td/><td/><td className="text-right text-amber-200 text-lg">{comp.toFixed(1)}</td></tr></tbody></table></P><div className="grid grid-cols-3 gap-3 text-center mb-4"><P><div className="text-xs text-gray-500">LLR</div><div className={`text-lg ${llr>0?"text-green-400":"text-red-400"}`}>{llr.toFixed(2)}</div></P><P><div className="text-xs text-gray-500">P(+)</div><div className="text-lg text-amber-300">{(prob*100).toFixed(1)}%</div></P><P><div className="text-xs text-gray-500">SPRT</div><div className="text-lg text-amber-400">{sprt.replace("_"," ")}</div></P></div><B onClick={()=>setStage(5)}>Proceed to Rule</B></div>}
    {stage===5&&<div><h2 className="text-lg font-light text-gray-300 mb-4">Stage 5: Rule</h2><div className="mb-4"><label className="text-xs text-gray-400 uppercase">Determination</label><textarea value={rul} onChange={e=>setRul(e.target.value)} rows={6} placeholder="State the ruling..." className="w-full bg-gray-900 border border-gray-800 rounded px-3 py-2 text-sm mt-1"/></div><div className="mb-4"><label className="text-xs text-gray-400 uppercase">Falsifiability <span className="text-red-400">*</span></label><textarea value={fal} onChange={e=>setFal(e.target.value)} rows={4} placeholder="What would change this ruling?" className="w-full bg-gray-900 border border-gray-800 rounded px-3 py-2 text-sm mt-1"/></div>{!fal&&<div className="text-red-400 text-xs mb-4 p-2 border border-red-400/30 rounded bg-red-400/5">UNFALSIFIABLE_WARNING — Gate G4 will fail</div>}<B onClick={()=>setStage(6)}>Proceed to Residual</B></div>}
    {stage===6&&<div><h2 className="text-lg font-light text-gray-300 mb-4">Stage 6: MirrorSolveRT</h2>{res.map((r,i)=><P key={i} className="mb-4"><div className="flex justify-between mb-2"><span className="text-xs text-amber-400">R{i+1}</span><select value={r.cat} onChange={e=>upR(i,"cat",e.target.value)} className="bg-gray-800 border border-gray-700 rounded px-2 py-1 text-xs"><option value="hard_constraint">Hard Constraint</option><option value="data_gap">Data Gap</option><option value="conflict">Conflict</option><option value="temporal">Temporal</option><option value="capacity">Capacity</option></select></div><input value={r.desc} onChange={e=>upR(i,"desc",e.target.value)} placeholder="What couldn't be optimized?" className="w-full bg-gray-800 border border-gray-700 rounded px-3 py-1.5 text-sm mb-2"/><input value={r.str} onChange={e=>upR(i,"str",e.target.value)} placeholder="Strategy..." className="w-full bg-gray-800 border border-gray-700 rounded px-3 py-1.5 text-sm mb-2"/><input value={r.goal} onChange={e=>upR(i,"goal",e.target.value)} placeholder="Goal + timeframe..." className="w-full bg-gray-800 border border-gray-700 rounded px-3 py-1.5 text-sm"/></P>)}<button onClick={addR} className="px-4 py-1.5 border border-gray-700 text-gray-400 text-xs rounded hover:border-gray-500 mb-4">+ Add Residual</button><br/><B onClick={()=>setStage(7)}>Proceed to Output</B></div>}
    {stage===7&&<div><h2 className="text-lg font-light text-gray-300 mb-4">Stage 7: Output</h2><div className="mb-4 p-4 border-2 border-amber-400/30 rounded bg-amber-400/5"><div className="text-xs text-amber-400 uppercase tracking-widest mb-3">Governance Gates</div>{[["G1: Register",ct!==""],["G2: Doctrine",true],["G3: Precedent",true],["G4: Falsifiability",fal.length>10],["G5: Residuals",res.length===0||res.every(r=>r.str.length>5)]].map(([l,p])=><div key={l} className="flex items-center gap-2 py-1"><span className={p?"text-green-400":"text-red-400"}>{p?"Y":"X"}</span><span className="text-sm">{l}</span></div>)}<div className={`mt-3 text-sm font-medium ${ok?"text-green-400":"text-red-400"}`}>{ok?"ALL GATES PASS":"GATE FAILURE"}</div></div><P className="mb-4"><div className="text-xs text-gray-500 uppercase tracking-widest mb-4">Compilation Complete</div><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-gray-400">Case</span><span>{cn}</span></div><div className="flex justify-between"><span className="text-gray-400">Domain</span><span className="capitalize">{ct.replace("-"," ")}</span></div><div className="flex justify-between"><span className="text-gray-400">Composite</span><span className="text-amber-300">{comp.toFixed(1)}</span></div><div className="flex justify-between"><span className="text-gray-400">LLR</span><span className={llr>0?"text-green-400":"text-red-400"}>{llr.toFixed(3)}</span></div><div className="flex justify-between"><span className="text-gray-400">SPRT</span><span>{sprt}</span></div><div className="flex justify-between"><span className="text-gray-400">Residuals</span><span>{res.length}</span></div></div><div className="mt-4 pt-4 border-t border-gray-800"><div className="text-xs text-gray-500 mb-2">DETERMINATION</div><div className="text-sm whitespace-pre-wrap">{rul||"(none)"}</div></div><div className="mt-4 pt-4 border-t border-gray-800"><div className="text-xs text-gray-500 mb-2">FALSIFIABILITY</div><div className="text-sm whitespace-pre-wrap">{fal||"(none)"}</div></div>{res.length>0&&<div className="mt-4 pt-4 border-t border-gray-800"><div className="text-xs text-gray-500 mb-2">RESIDUALS</div>{res.map((r,i)=><div key={i} className="mb-3 pl-3 border-l-2 border-amber-400/30"><div className="text-xs text-amber-400">R{i+1} [{r.cat}]</div><div className="text-sm">{r.desc}</div><div className="text-xs text-gray-500">Strategy: {r.str}</div><div className="text-xs text-gray-500">Goal: {r.goal}</div></div>)}</div>}</P><button onClick={()=>{setStage(0);setCt("");setCn("");setRul("");setFal("");setRes([])}} className="px-6 py-2 border border-gray-700 text-gray-400 text-sm rounded hover:border-gray-500">New Compilation</button></div>}
  </div></div>);
}